// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

console.log("Hello, BuckleScript and Reason!");

var body = {
  body: {
    username: "ds",
    password: "IsErsite8"
  }
};

console.log(body);

console.log((function (prim) {
        return JSON.stringify(prim);
      }));

var inst = Axios.create({
      baseURL: "https://loungeworks.flexrentalsolutions.com",
      headers: body
    });

var auth_url = "https://loungeworks.flexrentalsolutions.com/rest/core/authenticate";

exports.auth_url = auth_url;
exports.body = body;
exports.inst = inst;
/*  Not a pure module */
